# Netlify configuration file

[build]
  # Build command for setting up the serverless functions
  command = "npm run build"
  # Directory with static files
  publish = "public"
  # Define environment variables needed for the build
  environment = { NODE_VERSION = "18" }
  
# Redirect all requests to our server function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
  
# Add a redirect to handle root path access to the API properly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Define headers for CORS and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Let the server code handle CORS dynamically based on Origin
    # Access-Control-Allow-Origin is set by our server middleware
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, X-Custom-Header, Upgrade-Insecure-Requests, Access-Control-Allow-Origin"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
